version: "3.7"
services:
  redis:
    image: redis
    networks: 
      - webnet
  web:
    container_name: app_container
    image: test:1
    ports:
      - 5000:5000
    networks: ['webnet']
networks: 
  webnet: